---
title: "About"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
---

### NYC Shootings Dataset
This dataset, which is publicly available on the [NYC Open Data website](https://data.cityofnewyork.us/Public-Safety/NYPD-Shooting-Incident-Data-Historic-/833y-fsy8), includes every shooting incident that took place in New York City from 2006 to 2021. The Office of Management Analysis and Planning manually extracts and reviews the data on a quarterly basis before posting it on the NYPD website. 

Each record describes a shooting incident in one of the five NYC boroughs and offers demographic details about the victim and perpetrator, the time and location (latitude and longitude, type of property, etc) of the incident, and whether the shooting resulted in death. The NYC Open Data website offers the data so that the public can “explore the nature of shooting/criminal activity.” Our team of P8105 students was up to this challenge and performed a variety of exploratory analyses. 

<br>

### Codebook 
Below, we have described the variables included in this dataset, and have included comments about each:

<b>Incident_key:</b> randomly generated persistent ID for each arrest

<b>Occur_date:</b> exact date of the shooting incident

<b>Occur_time:</b> exact time of shooting incident

<b>Boro:</b> borough where the shooting incident occurred

<b>Precinct:</b> precinct where the shooting incident occurred

<b>Jurisdiction_code:</b> jurisdiction where the shooting incident occurred

<b>Location_desc:</b>  location of the shooting incident

<b>Statistical_murder_flag:</b> shooting results in the victim’s death, would be counted as a murder

<b>Perp_age_group:</b> perpetrator's age within a category

<b>Perp_sex:</b> perpetrator’s sex description

<b>Perp_race:</b> perpetrator’s race description

<b>Vic_age_group:</b> victim’s age within a category

<b>Vic_sex:</b> victim’s sex description

<b>Vic_race:</b> victim’s race description

<b>X_coord_cd:</b> midblock X-coordinate for New York State Plane Coordinate System

<b>Y_coord_cd:</b> midblock Y-coordinate for New York State Plane Coordinate System

<b>Latitude:</b> latitude coordinate for Global Coordinate System

<b>Longitude:</b> longitude coordinate for Global Coordinate System

<b>Lon_lat:</b> longitude and latitude coordinates for mapping
