---
title: "Animation + Additional Overview"
author: "Aakriti Shukla"
date: "2022-12-06"
output: html_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(patchwork)
library(plotly)
library(leaflet)

knitr::opts_chunk$set(
echo = TRUE,
warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%")

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis")

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```
```{r}
nypd_shooting_df = 
  read_csv("data/nypd_shooting_data.csv") %>%
  janitor::clean_names() %>%
  separate(col = occur_date, into = c("month", "day", "year"), sep = "/") %>% 
  separate(col = occur_time, into = c("hour", "minute", "second"), sep = ":") %>%
  mutate(across(where(is.character), tolower),
         month = as.numeric(month),
         month_name = recode(month, "1" = "january", "2" = "february", "3" = "march", "4" = "april", "5" = "may", "6" = "june", "7" = "july", "8" = "august", "9" = "september", "10" = "october", "11" = "november", "12" = "december"),
         day = as.numeric(day),
         year = as.numeric(year), 
         hour = as.numeric(hour),
         minute = as.numeric(minute), 
         second = as.numeric(second),
         minute_calc = hour * 60 + minute,
         boro = as.factor(boro), 
         boro = fct_relevel(boro, "manhattan", "brooklyn", "bronx", "queens", "staten island")) %>%
  select(incident_key, year, month_name, month, day, hour, minute, second, minute_calc, everything())
```

```{r}
victim_race_clean =
  nypd_shooting_df %>%
   mutate(
    vic_race = recode(vic_race, "black hispanic" = "hispanic", "white hispanic" = "hispanic"), 
    vic_race = na_if(vic_race, "unknown")) %>%
      filter(vic_race != "NA") %>%
  group_by(vic_race) %>%
  summarise(
    count = n()) %>%
  mutate(
    percentage = count / sum(count) * 100) %>%
  ggplot(aes(x = vic_race, y = count, color = vic_race, fill = vic_race)) +
  geom_bar(stat = "identity") +
  theme(
    axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 1),
    legend.position = "none") +
  labs(
    x = "",
    y = "Total") +
  ggtitle("Number of People Killed by Race")
```
 
```{r}
Perp_race_clean =
  nypd_shooting_df %>%
  mutate(
    perp_race = recode(perp_race, "black hispanic" = "hispanic", "white hispanic" = "hispanic"), 
    perp_race = na_if(perp_race, "unknown")
  ) %>%
   filter(perp_race != "NA") %>%
  group_by(perp_race) %>%
  summarise(
    count = n()) %>%
  mutate(
    percentage = count / sum(count) * 100) %>%
  ggplot(aes(x = perp_race, y = count, color = perp_race, fill = perp_perprace)) +
  geom_bar(stat = "identity") +
  theme(
    axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 1),
    legend.position = "none") +
  labs(
    x = "",
    y = "Total") +
  ggtitle("Number of Perpetrators by Race")
```
 
```{r}
Perp_age_group_clean =
  nypd_shooting_df %>%
  mutate(
    perp_age_group = na_if(perp_age_group, 1020),
    perp_age_group = na_if(perp_age_group, 224),
    perp_age_group = na_if(perp_age_group, 940),
    perp_age_group = na_if(perp_age_group, "unknown"),
  ) %>%
  filter(perp_age_group != "NA") %>%
  group_by(perp_age_group) %>%
  summarise(
    count = n()) %>%
  mutate(
    percentage = count / sum(count) * 100) %>%
  ggplot(aes(x = perp_age_group, y = count, color = perp_age_group, fill = perp_age_group)) +
  geom_bar(stat = "identity") +
  theme(
    axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 1),
    legend.position = "none") +
  labs(
    x = "",
    y = "Total") +
  ggtitle ("Perpetrators by Age")
 
```
 
```{r}
victim_age_group_clean =
  nypd_shooting_df %>%
  group_by(vic_age_group) %>%
  mutate(
    vic_age_group = na_if(vic_age_group, "unknown")
  ) %>%
  filter(vic_age_group != "NA") %>%
  summarise(
    count = n()) %>%
  mutate(
    percentage = count / sum(count) * 100) %>%
  ggplot(aes(x = vic_age_group, y = count, color = vic_age_group, fill = vic_age_group)) +
  geom_bar(stat = "identity") +
  theme(
    axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 1),
    legend.position = "none") +
  labs(
    x = "",
    y = "Total") +
  ggtitle ("Victims by Age")
 
```
 
```{r}
library(dplyr)
library(patchwork)
```
 
```{r}
vic_sex_clean =
  nypd_shooting_df %>%
  group_by(vic_sex) %>%
  mutate(
    vic_sex = na_if(vic_sex, "u")) %>%
  mutate(vic_sex = as.character(vic_sex), 
         vic_sex = recode(vic_sex, "f"='female', "m"= 'male')) %>%
  filter(vic_sex != "NA") %>%
  summarise(
    count = n()) %>%
  mutate(
    percentage = count / sum(count) * 100) %>%
  ggplot(aes(x = vic_sex, y = count, color = vic_sex, fill = vic_sex)) +
  geom_bar(stat = "identity") +
  theme(
    axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 1),
    legend.position = "none") +
  labs(
    x = "",
    y = "Total") +
  ggtitle ("Victims by Sex")
```
 
```{r}
perp_sex_clean = 
  nypd_shooting_df %>%
   mutate(
    perp_sex = na_if(perp_sex, "u")) %>%
   mutate(perp_sex = as.character(perp_sex), 
         perp_sex = recode(perp_sex, "f"='female', "m"= 'male')) %>%
  filter(perp_sex != "NA") %>%
  group_by(perp_sex) %>%
  summarise(
    count = n()) %>%
  mutate(
    percentage = count / sum(count) * 100) %>%
  ggplot(aes(x = perp_sex, y = count, color = perp_sex, fill = perp_sex)) +
  geom_bar(stat = "identity") +
  theme(
    axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 1),
    legend.position = "none") +
  labs(
    x = "",
    y = "Total") +
  ggtitle ("Perpetrators by Sex")
 
```
 
These are all the demographic plots togeher (victim and perpetrator)
```{r}
perp_sex_clean + Perp_age_group_clean + Perp_race_clean/ 
 
vic_sex_clean + victim_age_group_clean + victim_race_clean
```
